/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ComposantsRouteImport } from './routes/composants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemarrerRouteImport } from './routes/demarrer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as PlanDuSiteRouteImport } from './routes/plan-du-site'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as VerificationEmailRouteImport } from './routes/verification-email'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedPilotageRouteImport } from './routes/_authenticated/pilotage'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumTopicIdRouteImport } from './routes/forum.$topicId'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'
import { Route as MembresIndexRouteImport } from './routes/membres.index'
import { Route as MembresMemberIdRouteImport } from './routes/membres.$memberId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAbonnesRouteImport } from './routes/_authenticated/admin.abonnes'
import { Route as AuthenticatedAdminContenusRouteImport } from './routes/_authenticated/admin.contenus'
import { Route as AuthenticatedAdminForumRouteImport } from './routes/_authenticated/admin.forum'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminPilotageRouteImport } from './routes/_authenticated/admin.pilotage'
import { Route as AuthenticatedAdminTemoignagesRouteImport } from './routes/_authenticated/admin.temoignages'
import { Route as AuthenticatedMessagerieIndexRouteImport } from './routes/_authenticated/messagerie.index'
import { Route as AuthenticatedMessagerieConversationIdRouteImport } from './routes/_authenticated/messagerie.$conversationId'
import { Route as ForumCategorieSlugRouteImport } from './routes/forum.categorie.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposantsRoute = ComposantsRouteImport.update({
  id: '/composants',
  path: '/composants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarrerRoute = DemarrerRouteImport.update({
  id: '/demarrer',
  path: '/demarrer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDuSiteRoute = PlanDuSiteRouteImport.update({
  id: '/plan-du-site',
  path: '/plan-du-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification-email',
  path: '/verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotageRoute = AuthenticatedPilotageRouteImport.update({
  id: '/pilotage',
  path: '/pilotage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicIdRoute = ForumTopicIdRouteImport.update({
  id: '/forum/$topicId',
  path: '/forum/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresIndexRoute = MembresIndexRouteImport.update({
  id: '/membres/',
  path: '/membres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresMemberIdRoute = MembresMemberIdRouteImport.update({
  id: '/membres/$memberId',
  path: '/membres/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAbonnesRoute =
  AuthenticatedAdminAbonnesRouteImport.update({
    id: '/admin/abonnes',
    path: '/admin/abonnes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContenusRoute =
  AuthenticatedAdminContenusRouteImport.update({
    id: '/admin/contenus',
    path: '/admin/contenus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminForumRoute = AuthenticatedAdminForumRouteImport.update({
  id: '/admin/forum',
  path: '/admin/forum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPilotageRoute =
  AuthenticatedAdminPilotageRouteImport.update({
    id: '/admin/pilotage',
    path: '/admin/pilotage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTemoignagesRoute =
  AuthenticatedAdminTemoignagesRouteImport.update({
    id: '/admin/temoignages',
    path: '/admin/temoignages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagerieIndexRoute =
  AuthenticatedMessagerieIndexRouteImport.update({
    id: '/messagerie/',
    path: '/messagerie/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagerieConversationIdRoute =
  AuthenticatedMessagerieConversationIdRouteImport.update({
    id: '/messagerie/$conversationId',
    path: '/messagerie/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ForumCategorieSlugRoute = ForumCategorieSlugRouteImport.update({
  id: '/forum/categorie/$slug',
  path: '/forum/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/membres/': typeof MembresIndexRoute
  '/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/messagerie/': typeof AuthenticatedMessagerieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/pilotage': typeof AuthenticatedPilotageRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/blog': typeof BlogIndexRoute
  '/forum': typeof ForumIndexRoute
  '/membres': typeof MembresIndexRoute
  '/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/messagerie': typeof AuthenticatedMessagerieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/pilotage': typeof AuthenticatedPilotageRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/membres/': typeof MembresIndexRoute
  '/_authenticated/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/_authenticated/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/_authenticated/admin/forum': typeof AuthenticatedAdminForumRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/_authenticated/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/_authenticated/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/messagerie/': typeof AuthenticatedMessagerieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/plan-du-site'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/compte'
    | '/pilotage'
    | '/profil'
    | '/tableau-de-bord'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/membres/$memberId'
    | '/blog/'
    | '/forum/'
    | '/membres/'
    | '/admin/abonnes'
    | '/admin/contenus'
    | '/admin/forum'
    | '/admin/moderation'
    | '/admin/pilotage'
    | '/admin/temoignages'
    | '/messagerie/$conversationId'
    | '/forum/categorie/$slug'
    | '/admin/'
    | '/messagerie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/plan-du-site'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/compte'
    | '/pilotage'
    | '/profil'
    | '/tableau-de-bord'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/membres/$memberId'
    | '/blog'
    | '/forum'
    | '/membres'
    | '/admin/abonnes'
    | '/admin/contenus'
    | '/admin/forum'
    | '/admin/moderation'
    | '/admin/pilotage'
    | '/admin/temoignages'
    | '/messagerie/$conversationId'
    | '/forum/categorie/$slug'
    | '/admin'
    | '/messagerie'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/plan-du-site'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/_authenticated/compte'
    | '/_authenticated/pilotage'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/membres/$memberId'
    | '/blog/'
    | '/forum/'
    | '/membres/'
    | '/_authenticated/admin/abonnes'
    | '/_authenticated/admin/contenus'
    | '/_authenticated/admin/forum'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/pilotage'
    | '/_authenticated/admin/temoignages'
    | '/_authenticated/messagerie/$conversationId'
    | '/forum/categorie/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/messagerie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AvisRoute: typeof AvisRoute
  ComposantsRoute: typeof ComposantsRoute
  ContactRoute: typeof ContactRoute
  DemarrerRoute: typeof DemarrerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MerciRoute: typeof MerciRoute
  PlanDuSiteRoute: typeof PlanDuSiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ForumTopicIdRoute: typeof ForumTopicIdRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  MembresMemberIdRoute: typeof MembresMemberIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  MembresIndexRoute: typeof MembresIndexRoute
  ForumCategorieSlugRoute: typeof ForumCategorieSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composants': {
      id: '/composants'
      path: '/composants'
      fullPath: '/composants'
      preLoaderRoute: typeof ComposantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarrer': {
      id: '/demarrer'
      path: '/demarrer'
      fullPath: '/demarrer'
      preLoaderRoute: typeof DemarrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-du-site': {
      id: '/plan-du-site'
      path: '/plan-du-site'
      fullPath: '/plan-du-site'
      preLoaderRoute: typeof PlanDuSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-email': {
      id: '/verification-email'
      path: '/verification-email'
      fullPath: '/verification-email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilotage': {
      id: '/_authenticated/pilotage'
      path: '/pilotage'
      fullPath: '/pilotage'
      preLoaderRoute: typeof AuthenticatedPilotageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$topicId': {
      id: '/forum/$topicId'
      path: '/forum/$topicId'
      fullPath: '/forum/$topicId'
      preLoaderRoute: typeof ForumTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membres/': {
      id: '/membres/'
      path: '/membres'
      fullPath: '/membres/'
      preLoaderRoute: typeof MembresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membres/$memberId': {
      id: '/membres/$memberId'
      path: '/membres/$memberId'
      fullPath: '/membres/$memberId'
      preLoaderRoute: typeof MembresMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/abonnes': {
      id: '/_authenticated/admin/abonnes'
      path: '/admin/abonnes'
      fullPath: '/admin/abonnes'
      preLoaderRoute: typeof AuthenticatedAdminAbonnesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contenus': {
      id: '/_authenticated/admin/contenus'
      path: '/admin/contenus'
      fullPath: '/admin/contenus'
      preLoaderRoute: typeof AuthenticatedAdminContenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forum': {
      id: '/_authenticated/admin/forum'
      path: '/admin/forum'
      fullPath: '/admin/forum'
      preLoaderRoute: typeof AuthenticatedAdminForumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pilotage': {
      id: '/_authenticated/admin/pilotage'
      path: '/admin/pilotage'
      fullPath: '/admin/pilotage'
      preLoaderRoute: typeof AuthenticatedAdminPilotageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/temoignages': {
      id: '/_authenticated/admin/temoignages'
      path: '/admin/temoignages'
      fullPath: '/admin/temoignages'
      preLoaderRoute: typeof AuthenticatedAdminTemoignagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie/': {
      id: '/_authenticated/messagerie/'
      path: '/messagerie'
      fullPath: '/messagerie/'
      preLoaderRoute: typeof AuthenticatedMessagerieIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie/$conversationId': {
      id: '/_authenticated/messagerie/$conversationId'
      path: '/messagerie/$conversationId'
      fullPath: '/messagerie/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagerieConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forum/categorie/$slug': {
      id: '/forum/categorie/$slug'
      path: '/forum/categorie/$slug'
      fullPath: '/forum/categorie/$slug'
      preLoaderRoute: typeof ForumCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedPilotageRoute: typeof AuthenticatedPilotageRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedAdminAbonnesRoute: typeof AuthenticatedAdminAbonnesRoute
  AuthenticatedAdminContenusRoute: typeof AuthenticatedAdminContenusRoute
  AuthenticatedAdminForumRoute: typeof AuthenticatedAdminForumRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPilotageRoute: typeof AuthenticatedAdminPilotageRoute
  AuthenticatedAdminTemoignagesRoute: typeof AuthenticatedAdminTemoignagesRoute
  AuthenticatedMessagerieConversationIdRoute: typeof AuthenticatedMessagerieConversationIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMessagerieIndexRoute: typeof AuthenticatedMessagerieIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedPilotageRoute: AuthenticatedPilotageRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedAdminAbonnesRoute: AuthenticatedAdminAbonnesRoute,
  AuthenticatedAdminContenusRoute: AuthenticatedAdminContenusRoute,
  AuthenticatedAdminForumRoute: AuthenticatedAdminForumRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPilotageRoute: AuthenticatedAdminPilotageRoute,
  AuthenticatedAdminTemoignagesRoute: AuthenticatedAdminTemoignagesRoute,
  AuthenticatedMessagerieConversationIdRoute:
    AuthenticatedMessagerieConversationIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMessagerieIndexRoute: AuthenticatedMessagerieIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AvisRoute: AvisRoute,
  ComposantsRoute: ComposantsRoute,
  ContactRoute: ContactRoute,
  DemarrerRoute: DemarrerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MerciRoute: MerciRoute,
  PlanDuSiteRoute: PlanDuSiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  TemoignagesRoute: TemoignagesRoute,
  VerificationEmailRoute: VerificationEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  ForumTopicIdRoute: ForumTopicIdRoute,
  LegalCguRoute: LegalCguRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  MembresMemberIdRoute: MembresMemberIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  MembresIndexRoute: MembresIndexRoute,
  ForumCategorieSlugRoute: ForumCategorieSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
