/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ComposantsRouteImport } from './routes/composants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as VerificationEmailRouteImport } from './routes/verification-email'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumTopicIdRouteImport } from './routes/forum.$topicId'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposantsRoute = ComposantsRouteImport.update({
  id: '/composants',
  path: '/composants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification-email',
  path: '/verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicIdRoute = ForumTopicIdRouteImport.update({
  id: '/forum/$topicId',
  path: '/forum/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-email': typeof VerificationEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-email': typeof VerificationEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/blog': typeof BlogIndexRoute
  '/forum': typeof ForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/merci': typeof MerciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-email': typeof VerificationEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/blog/': typeof BlogIndexRoute
  '/forum/': typeof ForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-email'
    | '/admin'
    | '/compte'
    | '/profil'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/blog/'
    | '/forum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-email'
    | '/admin'
    | '/compte'
    | '/profil'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/blog'
    | '/forum'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/merci'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-email'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/_authenticated/profil'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/blog/'
    | '/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AvisRoute: typeof AvisRoute
  ComposantsRoute: typeof ComposantsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MerciRoute: typeof MerciRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ForumTopicIdRoute: typeof ForumTopicIdRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composants': {
      id: '/composants'
      path: '/composants'
      fullPath: '/composants'
      preLoaderRoute: typeof ComposantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-email': {
      id: '/verification-email'
      path: '/verification-email'
      fullPath: '/verification-email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$topicId': {
      id: '/forum/$topicId'
      path: '/forum/$topicId'
      fullPath: '/forum/$topicId'
      preLoaderRoute: typeof ForumTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AvisRoute: AvisRoute,
  ComposantsRoute: ComposantsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MerciRoute: MerciRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  VerificationEmailRoute: VerificationEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  ForumTopicIdRoute: ForumTopicIdRoute,
  LegalCguRoute: LegalCguRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  BlogIndexRoute: BlogIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
