-- Socle 1.6.0 : référentiel des activités (eqNAF), commun à tous les projets du Studio.
-- Source de vérité : table eqnaf de la base SCM (décision D-ESH-2026-10-06-01) ; ce bloc en est la
-- copie au 07/10/2026 (164 entrées, empreinte identique). Une mise à jour du registre = une version du socle.
-- 1. Table : lecture publique des activités actives, écriture réservée à l'administrateur.
CREATE TABLE IF NOT EXISTS public.activites (
  code text PRIMARY KEY,
  libelle text NOT NULL,
  type text NOT NULL CHECK (type IN ('professionnel', 'non_professionnel')),
  categorie text NOT NULL,
  cadran text CHECK (cadran IN ('E', 'S')),
  code_naf_2025 text,
  statut text NOT NULL DEFAULT 'actif' CHECK (statut IN ('actif', 'inactif')),
  source text NOT NULL DEFAULT 'Registre eqNAF, base SCM',
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activites_categorie_idx ON public.activites (categorie);
ALTER TABLE public.activites ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.activites FROM anon;
GRANT SELECT ON public.activites TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activites TO authenticated;
GRANT ALL ON public.activites TO service_role;
DROP POLICY IF EXISTS activites_lecture ON public.activites;
CREATE POLICY activites_lecture ON public.activites FOR SELECT TO anon, authenticated USING (statut = 'actif');
DROP POLICY IF EXISTS activites_admin ON public.activites;
CREATE POLICY activites_admin ON public.activites FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
DROP TRIGGER IF EXISTS activites_updated_at ON public.activites;
CREATE TRIGGER activites_updated_at BEFORE UPDATE ON public.activites
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
-- 2. Registre.
INSERT INTO public.activites (code, libelle, type, categorie, cadran, statut) VALUES
('01.13Z', 'Culture de légumes / melons / racines (maraîcher)', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('01.19Z', 'Autres cultures non permanentes', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('01.25Z', 'Culture d''autres fruits d''arbres ou d''arbustes et de fruits à coque', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('01.49Z', 'Élevage d''autres animaux (éleveur canin / félin / équin)', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('01.61Z', 'Activités de soutien aux cultures (paysagisme rural)', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('01.70Z', 'Chasse / piégeage et services annexes (guide nature / chasse)', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('02.40Z', 'Services de soutien à l''exploitation forestière', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('03.22Z', 'Aquaculture en eau douce (pisciculteur)', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('10.13B', 'Charcuterie (artisan charcutier / traiteur)', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('10.39B', 'Autres transformations et conservations de fruits et légumes (conserveur / confiturier)', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('10.71A', 'Fabrication industrielle de pain et de pâtisserie fraîche (boulanger artisan)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('10.71B', 'Cuisson de produits de boulangerie', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('10.71C', 'Boulangerie et boulangerie-pâtisserie', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('10.71D', 'Pâtisserie', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('10.82Z', 'Fabrication de cacao / chocolat et confiserie (chocolatier artisan)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('11.05Z', 'Fabrication de bière (brasseur artisanal)', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('13.92Z', 'Fabrication d''articles textiles sauf habillement (tapissier / brodeur)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('14.13Z', 'Fabrication de vêtements de dessus (couturier / styliste)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('14.19Z', 'Fabrication d''autres vêtements et accessoires (chapelier / modiste)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('15.12Z', 'Fabrication d''articles de voyage / maroquinerie / sellerie', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('16.29Z', 'Fabrication d''objets divers en bois (ébéniste / tourneur / sculpteur bois)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('18.12Z', 'Autre imprimerie (sérigraphie artisanale / impression textile)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('18.13Z', 'Activités de pré-presse (maquettiste / PAO)', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('23.41Z', 'Fabrication d''articles en céramique à usage domestique / ornemental (céramiste / potier)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('32.12Z', 'Fabrication d''articles de joaillerie et bijouterie', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('32.13Z', 'Fabrication d''articles de bijouterie fantaisie (créateur bijoux)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('32.99Z', 'Autres activités manufacturières n.c.a. (créateur objets / artisanat d''art)', 'professionnel', 'Artisanat & Métiers manuels', 'S', 'actif'),
('33.19Z', 'Réparation d''autres équipements (réparateur cycles / tondeuses)', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('43.21A', 'Travaux d''installation électrique (électricien)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.22A', 'Travaux d''installation d''eau et de gaz (plombier / chauffagiste)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.32A', 'Travaux de menuiserie bois et PVC', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.34Z', 'Travaux de peinture et vitrerie', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.39Z', 'Autres travaux de finition (carreleur / plâtrier / façadier)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.91A', 'Travaux de charpente (charpentier)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('43.91B', 'Travaux de couverture (couvreur / zingueur)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('46.19B', 'Autres intermédiaires du commerce en produits divers (courtier / apporteur d''affaires)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.19B', 'Autres commerces de détail en magasin non spécialisé (épicerie fine)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.78C', 'Autres commerces de détail spécialisés divers (boutique créateurs)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.81Z', 'Commerce de détail alimentaire sur éventaires et marchés', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.89Z', 'Autres commerces de détail sur éventaires et marchés (marché artisanal)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.91A', 'Vente à distance sur catalogue général (e-commerçant indépendant)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.91B', 'Vente à distance sur catalogue spécialisé', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.99A', 'Vente à domicile (VDI / marketing de réseau)', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('47.99B', 'Vente par automate et autres commerces de détail hors magasin', 'professionnel', 'Commerce & Vente', 'S', 'actif'),
('49.32Z', 'Transports de voyageurs par taxis (VTC / taxi)', 'professionnel', 'Transport & Livraison', 'S', 'actif'),
('49.41B', 'Transports routiers de fret de proximité (déménageur / livreur)', 'professionnel', 'Transport & Livraison', 'S', 'actif'),
('52.29A', 'Messagerie / fret express (livraison express indépendant)', 'professionnel', 'Transport & Livraison', 'S', 'actif'),
('53.20Z', 'Autres activités de poste et de courrier (coursier / livreur indépendant)', 'professionnel', 'Transport & Livraison', 'S', 'actif'),
('55.20Z', 'Hébergement touristique et autre hébergement de courte durée', 'professionnel', 'Immobilier', 'S', 'actif'),
('56.10A', 'Restauration traditionnelle', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('56.10B', 'Cafétérias et autres libres-services', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('56.10C', 'Restauration de type rapide (food truck / street food)', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('56.21Z', 'Services des traiteurs (traiteur événementiel / chef à domicile)', 'professionnel', 'Alimentation & Restauration', 'S', 'actif'),
('58.11Z', 'Édition de livres (auteur / auto-édition)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('58.14Z', 'Édition de revues et périodiques', 'professionnel', 'Arts & Création', 'S', 'actif'),
('59.11A', 'Production de films (vidéaste / réalisateur indépendant)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('59.11B', 'Production de films institutionnels et publicitaires', 'professionnel', 'Arts & Création', 'S', 'actif'),
('59.20Z', 'Enregistrement sonore et édition musicale', 'professionnel', 'Arts & Création', 'S', 'actif'),
('62.01Z', 'Programmation informatique (développeur freelance)', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('62.02A', 'Conseil en systèmes et logiciels informatiques', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('62.09Z', 'Autres activités informatiques (intégrateur / dépanneur)', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('63.11Z', 'Traitement de données / hébergement (webmaster / admin sys)', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('63.12Z', 'Portails internet (blogueur pro / éditeur de contenu web)', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('63.99Z', 'Autres services d''information (veille / curation / data)', 'professionnel', 'Numérique & Web', 'S', 'actif'),
('68.20B', 'Location de terrains et d''autres biens immobiliers (gîte / location saisonnière)', 'professionnel', 'Immobilier', 'S', 'actif'),
('68.31Z', 'Agences immobilières (agent / mandataire indépendant)', 'professionnel', 'Immobilier', 'S', 'actif'),
('68.32A', 'Administration d''immeubles et autres biens immobiliers', 'professionnel', 'Immobilier', 'S', 'actif'),
('69.10Z', 'Activités juridiques (avocat / juriste indépendant / médiateur)', 'professionnel', 'Conseil & Services professionnels', 'S', 'actif'),
('69.20Z', 'Activités comptables (expert-comptable / comptable indépendant)', 'professionnel', 'Conseil & Services professionnels', 'S', 'actif'),
('70.21Z', 'Conseil en relations publiques et communication', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('70.22Z', 'Conseil pour les affaires et autres conseils de gestion', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('71.11Z', 'Activités d''architecture', 'professionnel', 'Arts & Création', 'S', 'actif'),
('71.12B', 'Ingénierie / études techniques (ingénieur conseil / bureau d''études)', 'professionnel', 'Conseil & Services professionnels', 'S', 'actif'),
('71.20B', 'Analyses / essais et inspections techniques (diagnostiqueur immobilier)', 'professionnel', 'Conseil & Services professionnels', 'S', 'actif'),
('73.11Z', 'Activités des agences de publicité (freelance pub / créa)', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('73.12Z', 'Régie publicitaire de médias', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('73.20Z', 'Études de marché et sondages (consultant marketing)', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('74.10Z', 'Activités spécialisées de design (graphisme / UX / identité visuelle)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('74.20Z', 'Activités photographiques', 'professionnel', 'Arts & Création', 'S', 'actif'),
('74.30Z', 'Traduction et interprétation', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('74.90B', 'Activités spécialisées / scientifiques et techniques diverses', 'professionnel', 'Conseil & Services professionnels', 'S', 'actif'),
('75.00Z', 'Activités vétérinaires', 'professionnel', 'Agriculture & Nature', 'S', 'actif'),
('78.10Z', 'Activités des agences de placement de main-d''œuvre (coaching carrière)', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('79.11Z', 'Activités des agences de voyage', 'professionnel', 'Tourisme & Loisirs', 'S', 'actif'),
('79.12Z', 'Activités des voyagistes', 'professionnel', 'Tourisme & Loisirs', 'S', 'actif'),
('79.90Z', 'Autres services de réservation (conciergerie / guide touristique)', 'professionnel', 'Tourisme & Loisirs', 'S', 'actif'),
('81.21Z', 'Nettoyage courant des bâtiments', 'professionnel', 'Services à la personne', 'S', 'actif'),
('81.22Z', 'Autres activités de nettoyage (nettoyage spécialisé / remise en état)', 'professionnel', 'Services à la personne', 'S', 'actif'),
('81.30Z', 'Services d''aménagement paysager (paysagiste / jardinier)', 'professionnel', 'Bâtiment & Habitat', 'S', 'actif'),
('82.30Z', 'Organisation de foires / salons / congrès (événementiel)', 'professionnel', 'Communication & Marketing', 'S', 'actif'),
('85.51Z', 'Enseignement de disciplines sportives et d''activités de loisirs', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('85.52Z', 'Enseignement culturel (école de musique / danse / théâtre / arts)', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('85.59A', 'Formation continue d''adultes', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('85.59B', 'Autres enseignements (cours particuliers / soutien scolaire)', 'professionnel', 'Formation & Coaching', 'S', 'actif'),
('86.23Z', 'Pratique dentaire', 'professionnel', 'Bien-être & Santé', 'S', 'actif'),
('86.90D', 'Activités des infirmiers et sages-femmes libéraux', 'professionnel', 'Bien-être & Santé', 'S', 'actif'),
('86.90E', 'Activités des professionnels de la rééducation / ostéopathie', 'professionnel', 'Bien-être & Santé', 'S', 'actif'),
('86.90F', 'Activités de santé humaine non classées ailleurs (hypnothérapie / réflexologie)', 'professionnel', 'Bien-être & Santé', 'S', 'actif'),
('88.10A', 'Aide à domicile (auxiliaire de vie / aide ménagère)', 'professionnel', 'Services à la personne', 'S', 'actif'),
('88.99B', 'Action sociale sans hébergement n.c.a. (médiation / accompagnement social)', 'professionnel', 'Services à la personne', 'S', 'actif'),
('90.01Z', 'Arts du spectacle vivant (musicien / comédien / danseur)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('90.02Z', 'Activités de soutien au spectacle vivant (régie / son / lumière)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('90.03A', 'Création artistique relevant des arts plastiques', 'professionnel', 'Arts & Création', 'S', 'actif'),
('90.03B', 'Autre création artistique (écriture / illustration / design textile)', 'professionnel', 'Arts & Création', 'S', 'actif'),
('93.12Z', 'Activités de clubs de sports', 'professionnel', 'Sport & Fitness', 'S', 'actif'),
('93.13Z', 'Activités des centres de culture physique (coach sportif / salle de sport)', 'professionnel', 'Sport & Fitness', 'S', 'actif'),
('93.19Z', 'Autres activités liées au sport (préparateur physique / coach indépendant)', 'professionnel', 'Sport & Fitness', 'S', 'actif'),
('93.29Z', 'Autres activités récréatives et de loisirs (escape game / loisirs créatifs)', 'professionnel', 'Sport & Fitness', 'S', 'actif'),
('95.11Z', 'Réparation d''ordinateurs et d''équipements périphériques', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.12Z', 'Réparation d''équipements de communication (téléphones / tablettes)', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.21Z', 'Réparation de produits électroniques grand public', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.22Z', 'Réparation d''appareils électroménagers et d''équipements pour la maison', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.23Z', 'Réparation de chaussures et d''articles en cuir (cordonnier)', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.24Z', 'Réparation de meubles et d''équipements du foyer (tapissier / restaurateur)', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('95.29Z', 'Réparation d''autres biens personnels et domestiques (couturière / retoucheur)', 'professionnel', 'Réparation & Dépannage', 'S', 'actif'),
('96.02A', 'Coiffure', 'professionnel', 'Beauté & Esthétique', 'S', 'actif'),
('96.02B', 'Soins de beauté', 'professionnel', 'Beauté & Esthétique', 'S', 'actif'),
('96.04Z', 'Entretien corporel (bien-être / massage / sophrologie / naturopathie)', 'professionnel', 'Bien-être & Santé', 'S', 'actif'),
('96.09Z', 'Autres services personnels (tatouage / piercing / relooking)', 'professionnel', 'Beauté & Esthétique', 'S', 'actif'),
('97.00Z', 'Activités des ménages en tant qu''employeurs de personnel domestique', 'professionnel', 'Services à la personne', 'S', 'actif'),
('NP-ACA', 'Association caritative / humanitaire / solidarité', 'non_professionnel', 'Association & Bénévolat', 'E', 'actif'),
('NP-ACU', 'Association culturelle (patrimoine / histoire locale / langue)', 'non_professionnel', 'Association & Bénévolat', 'E', 'actif'),
('NP-AEN', 'Association environnementale / écologie / protection animale', 'non_professionnel', 'Association & Bénévolat', 'E', 'actif'),
('NP-ANI', 'Élevage amateur / passion animale (aquariophilie / reptiles / oiseaux)', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-APR', 'Association de parents d''élèves / parentalité', 'non_professionnel', 'Association & Bénévolat', 'E', 'actif'),
('NP-ASP', 'Association sportive / club amateur', 'non_professionnel', 'Association & Bénévolat', 'E', 'actif'),
('NP-BIJ', 'Création bijoux / accessoires (non déclaré)', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-BLG', 'Blog / newsletter indépendante (non monétisé)', 'non_professionnel', 'Médias & Contenu', 'E', 'actif'),
('NP-BOI', 'Travail du bois / menuiserie amateur', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-BOU', 'Bougies / déco / upcycling artisanal', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-BRO', 'Brocante / antiquités / vide-greniers amateur', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-COL', 'Collection (timbres / cartes / figurines / vinyles / vintage)', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-COU', 'Couture / tricot / crochet / macramé (créateur fait-main)', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-CUI', 'Cuisine / pâtisserie amateur (non déclaré / partage passion)', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-CYC', 'Cyclisme / VTT / vélo (communauté / groupe)', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-DAN', 'Danse amateur (cours / compagnie / solo)', 'non_professionnel', 'Arts & Spectacle amateur', 'E', 'actif'),
('NP-DIY', 'Bricolage / DIY / rénovation (partage passion)', 'non_professionnel', 'Écologie & Mode de vie', 'E', 'actif'),
('NP-ECO', 'Zéro déchet / minimalisme / mode de vie durable', 'non_professionnel', 'Écologie & Mode de vie', 'E', 'actif'),
('NP-ECR', 'Écriture / auto-édition amateur (roman / poésie / nouvelles / blog littéraire)', 'non_professionnel', 'Écriture & Édition', 'E', 'actif'),
('NP-EDU', 'Soutien scolaire bénévole / mentorat', 'non_professionnel', 'Parentalité & Éducation', 'E', 'actif'),
('NP-EQU', 'Équitation / sports équestres amateur', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-FIT', 'Fitness / musculation / CrossFit (partage transformation)', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-GEN', 'Généalogie / histoire familiale', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-INF', 'Influence / ambassadeur de marque amateur', 'non_professionnel', 'Médias & Contenu', 'E', 'actif'),
('NP-JAR', 'Jardinage / permaculture / potager partagé', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-JEU', 'Gaming / jeux de société / jeu de rôle (communauté)', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-MED', 'Médecines alternatives / lithothérapie / aromathérapie (non déclaré)', 'non_professionnel', 'Spiritualité & Développement', 'E', 'actif'),
('NP-MOD', 'Modélisme / maquettisme / miniatures', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-MOT', 'Passion véhicule (moto / auto / restauration / tuning)', 'non_professionnel', 'Passion & Collection', 'E', 'actif'),
('NP-MUS', 'Musique amateur (groupe / solo / composition / MAO)', 'non_professionnel', 'Arts & Spectacle amateur', 'E', 'actif'),
('NP-PAR', 'Parentalité alternative / éducation bienveillante / IEF', 'non_professionnel', 'Parentalité & Éducation', 'E', 'actif'),
('NP-PEI', 'Peinture / dessin / illustration amateur', 'non_professionnel', 'Arts visuels amateur', 'E', 'actif'),
('NP-PHO', 'Photographie amateur / club photo', 'non_professionnel', 'Arts visuels amateur', 'E', 'actif'),
('NP-POD', 'Podcast amateur / production audio indépendante', 'non_professionnel', 'Médias & Contenu', 'E', 'actif'),
('NP-RUN', 'Course à pied / trail / triathlon (communauté / groupe)', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-SAV', 'Savonnerie / cosmétique artisanale (non déclaré)', 'non_professionnel', 'Artisanat créatif', 'E', 'actif'),
('NP-SCU', 'Sculpture / modelage / céramique amateur', 'non_professionnel', 'Arts visuels amateur', 'E', 'actif'),
('NP-SPI', 'Spiritualité / astrologie / tarot / développement personnel (non pro)', 'non_professionnel', 'Spiritualité & Développement', 'E', 'actif'),
('NP-SPO', 'Sport amateur / coaching bénévole', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-THE', 'Théâtre amateur / troupe', 'non_professionnel', 'Arts & Spectacle amateur', 'E', 'actif'),
('NP-VEG', 'Végétarisme / véganisme / alimentation alternative', 'non_professionnel', 'Écologie & Mode de vie', 'E', 'actif'),
('NP-VOY', 'Voyage / aventure / vanlife / nomadisme', 'non_professionnel', 'Écologie & Mode de vie', 'E', 'actif'),
('NP-YOG', 'Yoga / méditation / développement personnel (non pro)', 'non_professionnel', 'Sport & Bien-être amateur', 'E', 'actif'),
('NP-YTB', 'Vidéo / YouTube / TikTok (créateur de contenu non monétisé)', 'non_professionnel', 'Médias & Contenu', 'E', 'actif')
ON CONFLICT (code) DO UPDATE SET libelle = excluded.libelle, type = excluded.type, categorie = excluded.categorie,
  cadran = excluded.cadran, statut = excluded.statut;
-- 3. Version.
INSERT INTO public.socle_versions (version, niveau, publie_le, resume, detail, migration_reference)
VALUES ('1.6.0', 'brique', '2026-10-07',
  'Référentiel des activités (eqNAF) : secteurs professionnels et passions, communs à tous les projets.',
  'Table activites (164 entrées du registre eqNAF de la base SCM : 120 codes NAF du cadran S, 44 activités non professionnelles du cadran E, 29 catégories), lecture publique des activités actives, écriture réservée à l''admin.',
  '20261007220000_v1_6_0_activites')
ON CONFLICT (version) DO NOTHING;
INSERT INTO public.site_settings (key, value)
VALUES ('socle', jsonb_build_object('version', '1.6.0', 'publie_le', '2026-10-07',
  'migration_reference', '20261007220000_v1_6_0_activites'))
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
WHERE string_to_array(coalesce(public.site_settings.value ->> 'version', '0.0.0'), '.')::int[]
      < string_to_array('1.6.0', '.')::int[];
